/***
Copyright 2019 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	snatv1 "github.com/noironetworks/aci-containers/pkg/snatallocation/apis/snat/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnatAllocations implements SnatAllocationInterface
type FakeSnatAllocations struct {
	Fake *FakeSnatV1
	ns   string
}

var snatallocationsResource = schema.GroupVersionResource{Group: "snat", Version: "v1", Resource: "snatallocations"}

var snatallocationsKind = schema.GroupVersionKind{Group: "snat", Version: "v1", Kind: "SnatAllocation"}

// Get takes name of the snatAllocation, and returns the corresponding snatAllocation object, and an error if there is any.
func (c *FakeSnatAllocations) Get(name string, options v1.GetOptions) (result *snatv1.SnatAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(snatallocationsResource, c.ns, name), &snatv1.SnatAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*snatv1.SnatAllocation), err
}

// List takes label and field selectors, and returns the list of SnatAllocations that match those selectors.
func (c *FakeSnatAllocations) List(opts v1.ListOptions) (result *snatv1.SnatAllocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(snatallocationsResource, snatallocationsKind, c.ns, opts), &snatv1.SnatAllocationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &snatv1.SnatAllocationList{ListMeta: obj.(*snatv1.SnatAllocationList).ListMeta}
	for _, item := range obj.(*snatv1.SnatAllocationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snatAllocations.
func (c *FakeSnatAllocations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(snatallocationsResource, c.ns, opts))

}

// Create takes the representation of a snatAllocation and creates it.  Returns the server's representation of the snatAllocation, and an error, if there is any.
func (c *FakeSnatAllocations) Create(snatAllocation *snatv1.SnatAllocation) (result *snatv1.SnatAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(snatallocationsResource, c.ns, snatAllocation), &snatv1.SnatAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*snatv1.SnatAllocation), err
}

// Update takes the representation of a snatAllocation and updates it. Returns the server's representation of the snatAllocation, and an error, if there is any.
func (c *FakeSnatAllocations) Update(snatAllocation *snatv1.SnatAllocation) (result *snatv1.SnatAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(snatallocationsResource, c.ns, snatAllocation), &snatv1.SnatAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*snatv1.SnatAllocation), err
}

// Delete takes name of the snatAllocation and deletes it. Returns an error if one occurs.
func (c *FakeSnatAllocations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(snatallocationsResource, c.ns, name), &snatv1.SnatAllocation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnatAllocations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(snatallocationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &snatv1.SnatAllocationList{})
	return err
}

// Patch applies the patch and returns the patched snatAllocation.
func (c *FakeSnatAllocations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *snatv1.SnatAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snatallocationsResource, c.ns, name, pt, data, subresources...), &snatv1.SnatAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*snatv1.SnatAllocation), err
}
