/***
Copyright 2019 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/noironetworks/aci-containers/pkg/nodeinfo/apis/aci.nodeinfo/v1"
	scheme "github.com/noironetworks/aci-containers/pkg/nodeinfo/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeinfoSpecsGetter has a method to return a NodeinfoSpecInterface.
// A group's client should implement this interface.
type NodeinfoSpecsGetter interface {
	NodeinfoSpecs(namespace string) NodeinfoSpecInterface
}

// NodeinfoSpecInterface has methods to work with NodeinfoSpec resources.
type NodeinfoSpecInterface interface {
	Create(*v1.NodeinfoSpec) (*v1.NodeinfoSpec, error)
	Update(*v1.NodeinfoSpec) (*v1.NodeinfoSpec, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NodeinfoSpec, error)
	List(opts metav1.ListOptions) (*v1.NodeinfoSpecList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeinfoSpec, err error)
	NodeinfoSpecExpansion
}

// nodeinfoSpecs implements NodeinfoSpecInterface
type nodeinfoSpecs struct {
	client rest.Interface
	ns     string
}

// newNodeinfoSpecs returns a NodeinfoSpecs
func newNodeinfoSpecs(c *AciV1Client, namespace string) *nodeinfoSpecs {
	return &nodeinfoSpecs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeinfoSpec, and returns the corresponding nodeinfoSpec object, and an error if there is any.
func (c *nodeinfoSpecs) Get(name string, options metav1.GetOptions) (result *v1.NodeinfoSpec, err error) {
	result = &v1.NodeinfoSpec{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeinfospecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeinfoSpecs that match those selectors.
func (c *nodeinfoSpecs) List(opts metav1.ListOptions) (result *v1.NodeinfoSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NodeinfoSpecList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeinfospecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeinfoSpecs.
func (c *nodeinfoSpecs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodeinfospecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a nodeinfoSpec and creates it.  Returns the server's representation of the nodeinfoSpec, and an error, if there is any.
func (c *nodeinfoSpecs) Create(nodeinfoSpec *v1.NodeinfoSpec) (result *v1.NodeinfoSpec, err error) {
	result = &v1.NodeinfoSpec{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodeinfospecs").
		Body(nodeinfoSpec).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodeinfoSpec and updates it. Returns the server's representation of the nodeinfoSpec, and an error, if there is any.
func (c *nodeinfoSpecs) Update(nodeinfoSpec *v1.NodeinfoSpec) (result *v1.NodeinfoSpec, err error) {
	result = &v1.NodeinfoSpec{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodeinfospecs").
		Name(nodeinfoSpec.Name).
		Body(nodeinfoSpec).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodeinfoSpec and deletes it. Returns an error if one occurs.
func (c *nodeinfoSpecs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeinfospecs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeinfoSpecs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeinfospecs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodeinfoSpec.
func (c *nodeinfoSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeinfoSpec, err error) {
	result = &v1.NodeinfoSpec{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodeinfospecs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
